name: track_my_bus
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  firebase_auth: ^6.1.1
  geolocator: ^14.0.2
  google_maps_flutter: ^2.13.1
  path_provider: ^2.1.5
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  google_fonts: ^6.3.2
  flutter_svg: ^2.2.2
  excel: ^4.0.6
  permission_handler: ^12.0.1
  open_filex: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Added for app icon generation
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  assets:
    - assets/

# App Icon Configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
